### ISSUE TITLE
react ts app `yarn test:unit` fails with `SyntaxError: Cannot use import statement outside a module`

### ISSUE THREAD

**Issue by pnwcoder2020** [sodatea/vite-jest#17]
Thank you for your work on this package and apologies in advance if this issue is the result of user error.

I see the following error in the example [react-app-ts](https://github.com/sodatea/vite-jest/tree/main/examples/react-app-ts) and also when incorporating `vite-jest` into my own react app.

```
/code/vite-jest/examples/react-app-ts/node_modules/vite-jest/bin/vite-jest.js:3
import fs from 'fs'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by mijamo** [comment]
I think this is a Yarn 2 specific problem, and to be more specific this is because Yarn 2 cannot currently run ES Modules.

See https://github.com/yarnpkg/berry/issues/638

When I try to run the example with pnpm it works, but not using yarn

**Comment by mason-smith** [comment]
@mijamo The error in my screenshot was with npm v7.19.0. I have not tried pnpm, although I did observe the same issue with Yarn 2 as you indicated as well.
