### ISSUE TITLE
Watch mode with `vite-jest --watch`

### ISSUE THREAD

**Issue by zigomir** [sodatea/vite-jest#32]
I can only press `a` once to re-run the tests, then after second run I get

```
  ● Test suite failed to run

    Server is not running.
```

and can't re-run tests anymore.

**Comment by sodatea** [comment]
Do you have a reproduction repo? I can't reproduce this in my projects.

**Comment by zigomir** [comment]
Hmm, happy to report I can't reproduce this anymore and `--watch` works as expected 🎉
Maybe I had some old vite/jest cache or something 🤷‍♂️

Thank you for this amazing library though, I had no real issues porting from `jest` to `vite-jest` and performance bump is 

`time npx jest --no-cache`

```
Executed in   20.00 secs    fish           external
   usr time   92.46 secs    0.41 millis   92.46 secs
   sys time    7.70 secs    1.10 millis    7.70 secs
```

vs

`time npx vite-jest --no-cache`
```
Executed in    8.98 secs    fish           external
   usr time    7.31 secs    0.38 millis    7.31 secs
   sys time    2.39 secs    1.35 millis    2.39 secs
```

**Comment by zigomir** [comment]
Spoke too soon. Watch seems to be working but when I change test file that should fail I still only see tests passing. I'm using vue 3 with typescript and `"@vue/test-utils": "^2.0.0-rc.17"`.

**Comment by zigomir** [comment]
I was now able to reproduce

```
  ● Test suite failed to run

    Server is not running.
```

running `npx vite-jest --watch` inside `vite-jest/examples/vue-app-ts` directory of this repo.

**Comment by sodatea** [comment]
Got it. It's due to the cache of the Vite dev server. I found an easy fix. Will patch it soon.

**Comment by zigomir** [comment]
@sodatea Actually I'm still getting this, but only every second re-run.

Output this time is:

```
  ● Test suite failed to run

    The server is not running

      at WebSocketServer.<anonymous> (node_modules/.pnpm/ws@8.3.0/node_modules/ws/lib/websocket-server.js:155:14)
      at emitClose (node_modules/.pnpm/ws@8.3.0/node_modules/ws/lib/websocket-server.js:442:10)
```

I'm using `vite@2.7.10` and `vite-jest@0.1.4`.

**Comment by straach** [comment]
I second this problem. Using the following:
```		
"vite": "2.8.6",
"vite-jest": "0.1.4"
```

**Comment by erik-with-a-k** [comment]
Also repro-ing this on

```
"vite": "2.9.6",
"vite-jest": "0.1.4"
```
